### ISSUE TITLE
maybe add lodash.camelCase

### ISSUE THREAD

**Issue by ruicsh** [smeijer/redux-define#2]
for their latest release (1.2.1), `redux-actions` removed `lodash.camelCase`: https://github.com/acdlite/redux-actions/releases

this means that the namespaced constants created by `redux-define` come with a "/" when used with `redux-actions`. Example:

```
const app = defineAction('app');
const START = app.defineAction('START').ACTION;
const actions = createActions({}, START);
```

will produce `actions.app/start` as the action creator name

I can call `camelCase` in my code, but need to do it for every `defineAction`.
do you any suggestion? thanks

**Comment by smeijer** [comment]
Are you saying that also the behavior of `createAction` changed? Somehow it's hard to believe they are manipulating typenames to be something else than I provide.

What is the outcome of:

```js
createAction('app/START');
```

It used to be:

```js
{ type: 'app/START', payload: .... }
```

**Comment by ruicsh** [comment]
`createAction` stayed the same.

it's `createActions` that has changed: the keys of the object returned by `createActions` are not camelCased as they used to be

**Comment by smeijer** [comment]
I've looked into `createActions`, and I understand your trouble. I'm not sure if this is something this library should be fixing, and when we do; how to solve this while maintaining backwards compatibility. 

The problem is not really in the created action, but more in the construction of this collection object (don't know how to name this differently).

I've created a test-sample here: https://runkit.com/smeijer/redux-define---issues-2, as you can see, the returned action is still:

```json
{
  "type": "app/START",
  "payload": {
    "foo": "bar"
  }
}
```

It is the `actions` object that has a naming like:

```
actions = {
  'app/start': () => ({ ...... }),
}
```

Do you have a suggestion on how to make it more easy for you?

**Comment by ruicsh** [comment]
I solved it in our code, with a helper function, like this:

in _helpers.js
```javascript
import _camelCase from 'lodash/camelCase';

export const actionsNames = (_actions) => {
  const actions = {};
  for (const action of Object.keys(_actions)) {
    actions[_camelCase(action)] = _actions[action];
  }
  return actions;
};
```

in constants.js
```javascript
import { defineAction } from 'redux-define';

const app = defineAction('app');
export const START = app.defineAction('START').ACTION;
```

in actions.js
```javascript
import * as c from './constants';
import { actionsNames } from './_helpers.js';

const actions = createActions({}, c.START);
export default {
  ...actionsNames(actions),
};
```

**Comment by smeijer** [comment]
I think your workaround is sufficient for now. I decided to not change anything about casing. It's not up to this library, nor up to `redux-actions` in my opinion. We just compose what the user is giving us.
